bot:
  token: your_discord_bot_token
  channel_id: 123456789012345678
  guild_id: 987654321098765432
database:
  host: localhost
  port: 5432
  user: your_username
  password: your_password
  database: your_database_name

attbot:
  template: ./staff_meeting_note.md